const LOAD_MOVIES = 'LOAD_MOVIES';
const LOAD_GENRES = 'LOAD_GENRES';
const GET_HDR_4K = 'GET_HDR_4K';
const GET_DESCRIPTION = 'GET_DESCRIPTION';
const LOAD_WEEK_MOVIES = 'LOAD_WEEK_MOVIES';
const LOAD_NEW_MOVIE = 'LOAD_NEW_MOVIE';
const LOAD_BEST_WEEK_MOVIE = 'LOAD_BEST_WEEK_MOVIE';
const LOAD_GENRES_LIST = 'LOAD_GENRES_LIST';

export {
  LOAD_MOVIES,
  LOAD_GENRES,
  GET_HDR_4K,
  GET_DESCRIPTION,
  LOAD_WEEK_MOVIES,
  LOAD_NEW_MOVIE,
  LOAD_BEST_WEEK_MOVIE,
  LOAD_GENRES_LIST
}